apiVersion: v1
kind: Pod
metadata:
  name: security-context-demo
spec:
  securityContext:
    runAsUser: 1000
    fsGroup: 2000
  containers:
  - name: container1
    image: alpine
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: data-volume
      mountPath: /data/demo
  - name: container2
    securityContext:
      runAsUser: 4000
      allowPrivilegeEscalation: false
    image: alpine
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: data-volume
      mountPath: /data/demo
  volumes:
  - name: data-volume
    emptyDir: {}