apiVersion: v1
kind: Service
metadata:
  name: ingress-servcie
  namespace: ingress-space
spec:
  ports:
  - name: 80-80
    port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30080
  selector:
    name: nginx-ingress    
  type: NodePort