apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: hello
    tier: frontend
    track: stable
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hello
      tier: frontend
      track: stable
  strategy: {}
  template:
    metadata:
      labels:
        app: hello
        tier: frontend
        track: stable
    spec:
      containers:
      - image: gcr.io/google-samples/hello-frontend:1.0
        name: hello-frontend
        lifecycle:
          preStop:
            exec:
              command: ["/usr/sbin/nginx","-s","quit"]