apiVersion: v1
kind: Service
metadata:
  labels:
    app: hello
    tier: frontend
    track: stable
  name: frontend
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: hello
    tier: frontend
    track: stable
  type: LoadBalancer
status:
  loadBalancer: {}
