apiVersion: v1
kind: Pod
metadata:
  name: startup
spec:
  containers:
  - name: startup
    image: httpd
    startupProbe:
      tcpSocket:
        port: 80
      initialDelaySeconds: 5
      periodSeconds: 5