apiVersion: v1
kind: ResourceQuota
metadata:
  name: marketing-quota
  namespace: marketing
spec:
  hard:
    pods: "10"
    requests.cpu: "2"
    requests.memory: 1Gi
    limits.cpu: "4"
    limits.memory: 2Gi