apiVersion: v1
kind: Pod
metadata:
  name: webserver
  namespace: web
spec:
  containers:
  - name: webserver
    image: nginx
    resources:
      requests:
        cpu: "0.5"
        memory: "512m"
      limits:
        cpu: "1"
        memory: "1024m"