apiVersion: v1
kind: Pod
metadata:
  name: hostdir
spec:
  containers:
  - name: hostdir
    image: alpine
    command: ['sh', '-c', 'sleep 3600']
    volumeMounts:
    - name: hostdir
      mountPath: /opt
  volumes:
  - name: hostdir
    hostPath:
      path: /tmp
      type: Directory