apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-1
spec:
  accessModes:
    - ReadWriteOnce # -ReadWriteMany -ReadOnlyMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data # example only, not suitable for production!