apiVersion: v1
kind: PersistentVolume
metadata:
  name: webserver-1-pv
spec:
  accessModes:
    - ReadOnlyMany
  capacity:
    storage: 1Gi
  hostPath:
    path: /tmp/data
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: webserver-1-pvc
spec:
  accessModes:
  - ReadOnlyMany
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
  - name: webserver
    image: nginx
    volumeMounts:
    - mountPath: /var/www/html
      name: webconfig
  volumes:
  - name: webconfig
    persistentVolumeClaim:
      claimName: webserver-1-pvc
