apiVersion: v1
kind: Pod
metadata:
  name: webserver
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: logs
      mountPath: /var/log/nginx
  - name: sidecar
    image: busybox
    volumeMounts:
    - name: logs
      mountPath: /var/log/nginx
    command: ['sh', '-c', 'while true; do if (grep -q "error" /var/log/nginx/error.log); then echo "Error discovered"; fi; sleep 10; done']
  volumes:
  - name: logs
    emptyDir: {}