apiVersion: batch/v1
kind: Job
metadata:
  name: hello
spec:
  completions: 3
  template:
    spec:
      containers:
      - name: hello
        image: busybox
        command: ['sh', '-c', 'echo Hello World']
      restartPolicy: Never
  backoffLimit: 4