apiVersion: v1
kind: PersistentVolume
metadata:
  name: mysql-pv
  labels:
    app: wordpress
spec:
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 20Gi
  hostPath:
    path: /tmp/share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: wordpress
spec:
  volumeName: mysql-pv
  storageClassName: manual
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 20Gi