apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-mysql
  labels:
    app: wordpress
    tier: backend
spec:
  selector:
    matchLabels:
      app: wordpress
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: wordpress
        tier: backend
    spec:
      containers:
      - name: mysql
        image: mysql:5.6
        env: 
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-pass
        ports:
        - containerPort: 3306
        volumeMounts:
        - name: mysql-persistent-storage
          mountPath: /var/lib/mysql
      volumes:
      - name: mysql-persistent-storage
        persistentVolumeClaim:
          claimName: mysql-pvc
