apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    environment: dev
  name: mypod
spec:
  containers:
  - args:
    - /bin/sh
    - -c
    - echo "Welcome to $ENVIRONMENT"
    env:
    - name: ENVIRONMENT
      value: dev
    image: busybox
    name: mypod
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
