apiVersion: v1
kind: Pod
metadata:
  name: my-pod
  labels:
    environment: dev
spec:
  serviceAccountName: default
  securityContext:
    runAsUser: 1001
    fsGroup: 1001
  containers:
  - name: my-container-1
    image: busybox
    command: ['sh', '-c', 'echo $ENVIRONMENT && sleep 3600']
    env:
    - name: ENVIRONMENT
      value: development