apiVersion: v1
kind: Pod
metadata:
  name: my-webapp
  labels:
    env: uat
spec:
  containers:
  - name: my-webapp
    image: nginx
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: size
            values:
            - large
            operator: In