apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secret
spec:
  containers:
  - name: pod-with-secret
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    env:
      - name: DB_PASSWORD
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: db_password
      - name: DB_ADMIN
        valueFrom:
          secretKeyRef:
            name: db-secrets
            key: db_admin_user
      