apiVersion: v1
kind: Pod
metadata:
  name: pod-with-secrets-from-env-vars
spec:
  containers:
  - name: pod-with-secrets-envvars
    image: busybox
    command: ['sh', '-c', 'sleep 3600']
    envFrom:
    - secretRef:
        name: db-secrets