apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: demo-pod
  name: demo-pod
spec:
  containers:
  - image: nginx
    name: demo-pod
    ports:
    - containerPort: 80
      name: nginx
    livenessProbe:
      httpGet:
        port: nginx
        path: /
      initialDelaySeconds: 5
      periodSeconds: 10
