apiVersion: v1
kind: PersistentVolume
metadata:
  name: demo-pv
spec:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 20Gi
  storageClassName: manual
  hostPath:
    path: /tmp/share/
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: demo-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi
  storageClassName: manual
---
apiVersion: v1
kind: Pod
metadata:
  name: demo-pod
spec:
  containers:
  - name: demo-pod
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: demo-pv
      mountPath: "/usr/share/nginx/html"
  volumes:
  - name: demo-pv
    persistentVolumeClaim:
      claimName: demo-pvc
  nodeSelector:
    nginx: config