apiVersion: v1
data:
  message: Hello World
kind: ConfigMap
metadata:
  name: demo-cm
---
apiVersion: v1
data:
  password: cGFzc3dvcmQ=
kind: Secret
metadata:
  name: demo-secret
---
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: demo-pod
  name: demo-pod
spec:
  containers:
  - command:
    - sleep
    - "3600"
    image: busybox
    name: demo-pod
    volumeMounts:
    - name: all-stuff-mount
      mountPath: /configs
  volumes:
  - name: all-stuff-mount
    projected:
      sources:
      - secret:
          name: demo-secret
          mode: 400
      - configMap:
          name: demo-cm

