apiVersion: v1
kind: ServiceAccount
metadata:
  creationTimestamp: null
  name: nginx-sa
---
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx-demo
  name: nginx-demo
spec:
  serviceAccountName: nginx-sa
  containers:
  - image: nginx
    name: nginx-demo
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
